services:
  generator:
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        - APP_NAME=pulse_generator
    environment:
      - LOG_LEVEL=debug
      - RNG_SCRIPT=python3 /app/python_example/get_randomness.py
      # - PREPARE_CRON_SCHEDULE="50 * * * * *" # every 50th second of the minute
    command: ["/app/pulse_generator"]
    networks:
      - internal

networks:
  internal: