services:
  generator:
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        - APP_NAME=pulse_generator
    command: ["/app/pulse_generator"]
    networks:
      - internal

  rng_factory:
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        - APP_NAME=rng_factory
    command: ["/app/rng_factory"]
    networks:
      - internal
    depends_on:
      - generator

networks:
  internal: