services:
  generator:
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        - APP_NAME=pulse_generator
    environment:
      - LOG_LEVEL=debug
      - RNG_SCRIPT=python3 /app/python_example/get_randomness.py
      # - PREPARE_CRON_SCHEDULE="50 * * * * *" # every 50th second of the minute
    command: ["/app/pulse_generator"]
    networks:
      - internal

  # rng_factory:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.base
  #     args:
  #       - APP_NAME=rng_factory
  #   environment:
  #     - LOG_LEVEL=debug
  #     - RNG_SCRIPT_PATH=/app/python_example/get_randomness.py
  #   command: ["/app/rng_factory"]
  #   networks:
  #     - internal
  #   depends_on:
  #     - generator

networks:
  internal: