[package]
name = "rng_factory"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rng_factory"
path = "src/main.rs"

[dependencies]
biab_utils = { path = "../biab_utils" }
tokio = { version = "1.43.0", features = ["full"] }
log = "0.4.25"