[package]
name = "pulse_generator"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "pulse_generator"
path = "src/main.rs"

[dependencies]
twine = { git = "https://github.com/twine-protocol/twine-rs.git", rev = "f625e59963014f19257d596a8e3ebec61f0dbcf4", features = ["build", "rsa"] }
twine_http_store =  { git = "https://github.com/twine-protocol/twine-rs.git", rev = "f625e59963014f19257d596a8e3ebec61f0dbcf4", package = "twine_http_store" }
twine_sql_store = { git = "https://github.com/twine-protocol/twine-rs.git", rev = "f625e59963014f19257d596a8e3ebec61f0dbcf4", package = "twine_sql_store", features = ["mysql", "runtime-tokio"]}
biab_utils = { path = "../biab_utils" }
futures = "0.3.31"
tokio = { version = "1.43.0", features = ["full"] }
log = "0.4.25"
anyhow = "1.0.44"
serde = { version = "1.0.130", features = ["derive"] }
chrono = { version = "0.4.39", features = ["serde"] }
serde_yaml = "0.9.34+deprecated"
serde_with = "3.12.0"
