[package]
name = "pulse_generator"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "pulse_generator"
path = "src/main.rs"

[dependencies]
twine = { git = "https://github.com/twine-protocol/twine-rs.git", rev = "3b66b8bf4e8e0b8592ee3e0df075b010937b5a12", features = ["build", "rsa"] }
twine_http_store =  { git = "https://github.com/twine-protocol/twine-rs.git", rev = "3b66b8bf4e8e0b8592ee3e0df075b010937b5a12", package = "twine_http_store" }
twine_sql_store = { git = "https://github.com/twine-protocol/twine-rs.git", rev = "3b66b8bf4e8e0b8592ee3e0df075b010937b5a12", package = "twine_sql_store", features = ["mysql", "runtime-tokio"]}
twine_spec_rng = { git = "https://github.com/twine-protocol/twine_spec_rng", rev = "7d035f328641f5a253dbb1d94906c8093085beac" }
biab_utils = { path = "../biab_utils" }
futures = "0.3.31"
tokio = { version = "1.43.0", features = ["full"] }
log = "0.4.25"
anyhow = "1.0.44"
serde = { version = "1.0.130", features = ["derive"] }
chrono = { version = "0.4.39", features = ["serde"] }
serde_yaml = "0.9.34"
serde_with = "3.12.0"
yubihsm = { version = "0.42.1", features = ["http-server", "usb", "passwords", "untested"] }